export { h } from './h'
export { renderSlots } from './helpers/renderSlots'
export { createTextVNode } from './vNode'
export { getCurrentInstance } from './component'
export { provide, inject } from './apiInject'
export { createRenderer } from './renderer'
